#!/bin/bash
# deploy-to-vps.sh -- one-shot VPS setup for the spacetime-lab MCP bridge.
#
# Runs ON the VPS (Ubuntu 22.04 / Debian 12 recommended, ARM or x86).
# Installs Caddy + WireGuard, configures both, brings up the tunnel,
# starts Caddy with auto Let's Encrypt, and prints the VPS's WireGuard
# public key (which you then paste into the PC-side config).
#
# Usage (on the VPS, as root or via sudo):
#
#   DOMAIN=mcp.chernandez.dev \
#   PC_CLIENT_PUBKEY='x+3MzNekqmFFscz22UuzBr+IwduJ3d0QH7NeVSQbiHM=' \
#   ADMIN_EMAIL=you@example.com \
#   bash deploy-to-vps.sh
#
# Required environment variables:
#   DOMAIN           -- the public hostname that claude.ai will reach
#                       (e.g., mcp.chernandez.dev). Must already resolve
#                       to this VPS IP before running.
#   PC_CLIENT_PUBKEY -- base64 WireGuard public key of the PC client.
#                       Obtained from:
#                         python .agent/_wrapper/wg_keygen.py --show
#                       on the PC.
#   ADMIN_EMAIL      -- email Caddy sends to Let's Encrypt for ACME.
#                       Real address required: LE uses it for expiry
#                       warnings.
#
# Optional:
#   WG_PORT          -- UDP port WireGuard listens on (default 51820).
#                       If your ISP blocks 51820 on the PC side, use 443.
#
# Idempotent-ish: rerunning overwrites /etc/wireguard/wg0.conf and
# /etc/caddy/Caddyfile with fresh values.  The VPS's own WireGuard
# keypair at /etc/wireguard/wg0-private.key is preserved on rerun (so
# the PC-side config stays valid).

set -euo pipefail

# ---------------------------------------------------------------------------
# Input validation
# ---------------------------------------------------------------------------

: "${DOMAIN:?set DOMAIN env var (e.g., mcp.chernandez.dev)}"
: "${PC_CLIENT_PUBKEY:?set PC_CLIENT_PUBKEY env var (wg-pc-client-public.key)}"
: "${ADMIN_EMAIL:?set ADMIN_EMAIL env var (Let's Encrypt contact)}"
WG_PORT="${WG_PORT:-51820}"
WG_NET="10.8.0.0/24"
WG_SERVER_IP="10.8.0.1"
WG_CLIENT_IP="10.8.0.2"

echo "=== inputs ==="
echo "  DOMAIN           : $DOMAIN"
echo "  ADMIN_EMAIL      : $ADMIN_EMAIL"
echo "  PC_CLIENT_PUBKEY : ${PC_CLIENT_PUBKEY:0:12}..."
echo "  WG_PORT          : $WG_PORT"
echo "  WG network       : $WG_NET  (server=$WG_SERVER_IP, pc=$WG_CLIENT_IP)"
echo ""

# ---------------------------------------------------------------------------
# Root check
# ---------------------------------------------------------------------------

if [ "$(id -u)" -ne 0 ]; then
    echo "Must run as root. Rerun with: sudo -E bash deploy-to-vps.sh" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 1. Install deps
# ---------------------------------------------------------------------------

echo "=== 1. Installing Caddy + WireGuard ==="
apt-get update -y

# Caddy repo (official)
if ! command -v caddy >/dev/null; then
    apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
        > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -y
    apt-get install -y caddy
fi

apt-get install -y wireguard-tools iptables

# ---------------------------------------------------------------------------
# 2. WireGuard server keypair (preserve if exists)
# ---------------------------------------------------------------------------

echo ""
echo "=== 2. WireGuard server keypair ==="
cd /etc/wireguard
umask 077

if [ ! -f wg0-private.key ]; then
    echo "  generating new keypair"
    wg genkey | tee wg0-private.key | wg pubkey > wg0-public.key
else
    echo "  reusing existing keypair (delete wg0-private.key to regenerate)"
fi

SERVER_PRIV=$(cat /etc/wireguard/wg0-private.key)
SERVER_PUB=$(cat /etc/wireguard/wg0-public.key)

# ---------------------------------------------------------------------------
# 3. Write wg0.conf
# ---------------------------------------------------------------------------

echo ""
echo "=== 3. Writing /etc/wireguard/wg0.conf ==="

# Detect the default outbound interface (needed for MASQUERADE rule)
DEFAULT_IF=$(ip route | awk '/^default/ {print $5; exit}')
echo "  default interface: $DEFAULT_IF"

cat > /etc/wireguard/wg0.conf <<EOF
# spacetime-lab MCP bridge -- VPS side
# Generated by deploy-to-vps.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

[Interface]
PrivateKey = $SERVER_PRIV
Address = $WG_SERVER_IP/24
ListenPort = $WG_PORT
PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o $DEFAULT_IF -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o $DEFAULT_IF -j MASQUERADE

[Peer]
# pc-client (christian's desktop)
PublicKey = $PC_CLIENT_PUBKEY
AllowedIPs = $WG_CLIENT_IP/32
EOF

chmod 600 /etc/wireguard/wg0.conf

# Enable IP forwarding (needed for the MASQUERADE rule above)
sysctl -w net.ipv4.ip_forward=1 >/dev/null
if ! grep -q "^net.ipv4.ip_forward=1" /etc/sysctl.conf; then
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
fi

# ---------------------------------------------------------------------------
# 4. Start WireGuard
# ---------------------------------------------------------------------------

echo ""
echo "=== 4. Starting WireGuard ==="
systemctl enable --now wg-quick@wg0
sleep 1
wg show wg0 || {
    echo "WireGuard failed to start. Check: journalctl -xeu wg-quick@wg0" >&2
    exit 1
}

# ---------------------------------------------------------------------------
# 5. Configure Caddy reverse proxy -> WG client IP
# ---------------------------------------------------------------------------

echo ""
echo "=== 5. Writing /etc/caddy/Caddyfile ==="

cat > /etc/caddy/Caddyfile <<EOF
# spacetime-lab MCP bridge -- Caddy reverse proxy with auto Let's Encrypt.
{
    email $ADMIN_EMAIL
}

$DOMAIN {
    # Forward all traffic into the WireGuard tunnel to the PC's MCP server.
    # Auth is enforced at the MCP server layer via X-MCP-Token header;
    # Caddy just does TLS + proxy.
    reverse_proxy $WG_CLIENT_IP:8765 {
        # Preserve client IP for the MCP server's auth logs.
        header_up X-Forwarded-For {remote_host}
    }

    log {
        output file /var/log/caddy/mcp.log {
            roll_size 10MiB
            roll_keep 5
        }
        format json
    }

    # Reasonable defaults; tighten as needed.
    header {
        Strict-Transport-Security "max-age=31536000"
        X-Content-Type-Options nosniff
    }
}
EOF

mkdir -p /var/log/caddy
systemctl reload caddy

# ---------------------------------------------------------------------------
# 6. Firewall (ufw if present, iptables fallback)
# ---------------------------------------------------------------------------

echo ""
echo "=== 6. Firewall ==="
if command -v ufw >/dev/null 2>&1; then
    ufw allow 22/tcp        # SSH
    ufw allow 80/tcp        # Caddy HTTP challenge
    ufw allow 443/tcp       # Caddy HTTPS
    ufw allow ${WG_PORT}/udp # WireGuard
    ufw --force enable || true
    ufw status verbose || true
else
    echo "  ufw not installed; assuming cloud firewall rules already allow the ports."
fi

# ---------------------------------------------------------------------------
# 7. Summary
# ---------------------------------------------------------------------------

VPS_PUBLIC_IP="$(curl -s -4 https://ifconfig.me || echo '<detect manually>')"

echo ""
echo "======================================================================"
echo "=== DEPLOY COMPLETE"
echo "======================================================================"
echo ""
echo "VPS public IP    : $VPS_PUBLIC_IP"
echo "VPS WG public key: $SERVER_PUB"
echo "VPS WG endpoint  : $VPS_PUBLIC_IP:$WG_PORT"
echo "Domain           : $DOMAIN"
echo "MCP URL          : https://$DOMAIN  (TLS cert being issued on first visit)"
echo ""
echo "=== NEXT STEPS (on your PC) ==="
echo ""
echo "1. Install WireGuard for Windows (elevated):"
echo "     winget install WireGuard.WireGuard"
echo ""
echo "2. Import this config into the WireGuard app (save as spacetime-bridge.conf):"
echo ""
echo "   ----- copy below -----"
echo "   [Interface]"
echo "   PrivateKey = <paste from ~/.spacetime-bridge/wg-pc-client-private.key>"
echo "   Address    = $WG_CLIENT_IP/24"
echo ""
echo "   [Peer]"
echo "   PublicKey           = $SERVER_PUB"
echo "   Endpoint            = $VPS_PUBLIC_IP:$WG_PORT"
echo "   AllowedIPs          = $WG_SERVER_IP/32"
echo "   PersistentKeepalive = 25"
echo "   ----- copy above -----"
echo ""
echo "3. Activate the tunnel in the WireGuard app."
echo ""
echo "4. Change MCP server to bind to the WG IP:"
echo "     In your Startup folder launcher, set"
echo "     MCP_BIND=$WG_CLIENT_IP:8765  (currently 127.0.0.1:8765)"
echo "   Restart the MCP server so Caddy can reach it."
echo ""
echo "5. Test from the VPS that the tunnel reaches the PC's MCP server:"
echo "     curl -sk -H 'X-MCP-Token: <token>' https://$WG_CLIENT_IP:8765/mcp/... (expect: 200/400)"
echo ""
echo "6. From anywhere on the internet (e.g., phone LTE):"
echo "     curl -s https://$DOMAIN"
echo "   (401 without token, handshake OK with token)"
echo ""
echo "7. Register as Custom Connector in claude.ai:"
echo "     Settings -> Connectors -> Add custom connector"
echo "     URL: https://$DOMAIN"
echo "     Header: X-MCP-Token: <your token>"
echo ""
